In [1]:
from pycaret.regression import load_model, predict_model
import pandas as pd

In [2]:
model = load_model("regression_pipeline")

Transformation Pipeline and Model Successfully Loaded

In [ ]:
print(f"To jest model: {model}")

In [3]:
df = pd.DataFrame([
    {"x": 10},
    {"X": 30},
    {"x": 80}
])

predict_model(model, data=df)

      x     X  prediction_label
0  10.0   NaN         21.194849
1   NaN  30.0        200.618290
2  80.0   NaN        160.439195

In [4]:
def predict_value(df, predicted_column_name="predicted"):
    model = load_model("regression_pipeline")
    df = predict_model(model, data=df)

    df = df.rename(columns={"prediction_label": predicted_column_name})
    return df

In [5]:
predict_value(
    df=pd.DataFrame([
        {"x": 2},
        {"X": 60},
        {"x": 211}
    ]),
    predicted_column_name="predicted_y"
)

Transformation Pipeline and Model Successfully Loaded

       x     X  predicted_y
0    2.0   NaN     5.281209
1    NaN  60.0   200.618290
2  211.0   NaN   421.025042